DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS cart_menu_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS restaurant_details CASCADE;

CREATE TABLE carts (
id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
total DECIMAL(4,2),
ordered_status BOOLEAN DEFAULT FALSE
);

CREATE TABLE categories (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL
);


CREATE TABLE menu_items (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
price DECIMAL(4,2) NOT NULL,
picture_url VARCHAR(255),
description VARCHAR(255),
category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);


CREATE TABLE cart_menu_items (
cart_id INTEGER REFERENCES carts(id) ON DELETE CASCADE,
menu_item_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
quantity SMALLINT NOT NULL DEFAULT 1,
unique(cart_id,menu_item_id)
);


CREATE TABLE orders (
id SERIAL PRIMARY KEY NOT NULL,
time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT NULL,
pickup_time TIME DEFAULT NULL,
total DECIMAL(19,2) NOT NULL,
picked_up BOOLEAN DEFAULT FALSE
);


CREATE TABLE restaurant_details (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
phone VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
street_address VARCHAR(255) NOT NULL,
city VARCHAR(255) NOT NULL,
province VARCHAR(255) NOT NULL,
postal_code VARCHAR(255) NOT NULL,
website VARCHAR(255) NOT NULL,
active BOOLEAN DEFAULT TRUE
);
